settings:
  lib_name: buffer_pex_sky130_tt_1v80_025C

  units:
    time: ns
    voltage: V
    current: uA
    pulling_resistance: kOhm
    leakage_power: nW
    capacitive_load: pF
    energy: fJ

  named_nodes:
    primary_power:
      name: VDD
      voltage: 1.8

    primary_ground:
      name: VSS
      voltage: 0

    nwell:
      name: VNW
      voltage: 1.8

    pwell:
      name: VPW
      voltage: 0

  temperature: 25

  simulation:
    backend: ngspice-subprocess

  results_dir: results
  debug: false
  omit_on_failure: false

cells:
  buffer_without_load:
    netlist: cells/buffer_pex_dcfix.spice

    models:
      - sky130A/libs.tech/ngspice/sky130.lib.spice tt

    inputs:
      - A

    outputs:
      - Y

    functions:
      - Y=A

    data_slews:
      - 0.01
      - 0.05
      - 0.2
      - 1.0

    loads:
      - 0.0005
      - 0.002
      - 0.01
      - 0.05
